In [36]:
import csv
import pandas as pd 
import numpy as np
from math import sqrt
from tqdm.notebook import tqdm

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error 
from statsmodels.stats.outliers_influence import variance_inflation_factor

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVR
from lightgbm import LGBMRegressor

In [37]:
df_MoR_0 = pd.read_excel(r'../Data/Data_MoR.xlsx')
df_CS_0 = pd.read_excel(r'../Data/Data_CS.xlsx')

### Train ML Models

### MoR

In [38]:
df_MoR_1 = df_MoR_0[['FA/CM', 'FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Max CA Agg (mm)', 'Converted CS', 'FS Value']]     
Train, Test = train_test_split(df_MoR_1, test_size=0.2, random_state=21)

Train = Train.dropna()  
Test = Test.dropna()

xtrain = Train[['FA/CM', 'FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Max CA Agg (mm)', 'Converted CS']]     
ytrain = Train[['FS Value']]

xtest = Test[['FA/CM', 'FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Max CA Agg (mm)', 'Converted CS']]      
ytest = Test[['FS Value']]

#xtrain = xtrain.dropna()  
#xtest = xtest.dropna() 

#sc = MinMaxScaler()
#xtrain = sc.fit_transform(xtrain)
#xtest = sc.transform(xtest)  
reg = LGBMRegressor(n_estimators=250, verbose=-1);
reg.fit(xtrain, ytrain)

#Train
print(len(xtrain), len(xtest))
print("Train_R2", r2_score(ytrain, reg.predict(xtrain)))
print("Train_MSE", mean_squared_error(ytrain, reg.predict(xtrain)))

print("Test", r2_score(ytest, reg.predict(xtest)))
print("Test_MSE", mean_squared_error(ytest, reg.predict(xtest)))

351 88
Train_R2 0.97682758868099
Train_MSE 0.1091696912141736
Test 0.90136195494754
Test_MSE 0.5054392455374107


In [39]:
xtrain_MoR = df_MoR_1[['FA/CM', 'FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Max CA Agg (mm)', 'Converted CS']]     
ytrain_MoR = df_MoR_1[['FS Value']]

reg_MoR = LGBMRegressor(n_estimators=250, verbose=-1);
reg_MoR.fit(xtrain_MoR, ytrain_MoR)

#Train
print(len(xtrain_MoR), len(ytrain_MoR))
print("Train_R2", r2_score(ytrain_MoR, reg_MoR.predict(xtrain_MoR)))
print("Train_MSE", mean_squared_error(ytrain_MoR, reg_MoR.predict(xtrain_MoR)))

439 439
Train_R2 0.9810492477533723
Train_MSE 0.09088998976573659


In [40]:
print(reg_MoR.predict(np.array([1.85, 0.66, 118, 0.55, 35,  16., 70.8]).reshape(1,-1)),
      reg_MoR.predict(np.array([1.85, 0.67, 118, 0.55, 35,  16., 102]).reshape(1,-1)))

[9.30637536] [11.4056164]


In [41]:
## from statsmodels.stats.outliers_influence import variance_inflation_factor
# VIF dataframe
VIF_MOR = df_MoR_1.copy()
VIF_MOR = VIF_MOR.drop(['FS Value'], axis =1).dropna()

vif_data = pd.DataFrame()
vif_data["feature"] = VIF_MOR.columns

# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(VIF_MOR.values, i)
                          for i in range(len(VIF_MOR.columns))]
  
print(vif_data)

           feature        VIF
0            FA/CM  17.858736
1            FA/CA   7.590489
2      Steel Fibre   3.770946
3        S Fibre D  55.928241
4        S Fibre L  48.173574
5  Max CA Agg (mm)  11.685581
6     Converted CS   6.036243


### CS

In [42]:
df_CS_1 = df_CS_0[['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                   'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'CS Age', 'Co Type', 
                   'CS Value']]     
Train, Test = train_test_split(df_CS_1, test_size=0.3, random_state=41)

Train = Train.dropna()  
Test = Test.dropna()

xtrain = Train[['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 
                'CS Age', 'Co Type']]     
ytrain = Train[['CS Value']]

xtest = Test[['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 
                'CS Age', 'Co Type']]      
ytest = Test[['CS Value']]

#xtrain = xtrain.dropna()  
#xtest = xtest.dropna() 

#sc = MinMaxScaler()
#xtrain = sc.fit_transform(xtrain)
#xtest = sc.transform(xtest)  
reg = LGBMRegressor(n_estimators=400, verbose=-1);
reg.fit(xtrain, ytrain)

#Train
print(len(xtrain), len(xtest))
print("Train_R2", r2_score(ytrain, reg.predict(xtrain)))
print("Train_MSE", mean_squared_error(ytrain, reg.predict(xtrain)))

print("Test", r2_score(ytest, reg.predict(xtest)))
print("Test_MSE", mean_squared_error(ytest, reg.predict(xtest)))

810 348
Train_R2 0.9971504986435632
Train_MSE 1.2696688196648447
Test 0.9640422155688602
Test_MSE 17.876099351214055


In [43]:
xtrain_CS = df_CS_1[['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'CS Age', 'Co Type']]     
ytrain_CS = df_CS_1[['CS Value']]

reg_CS = LGBMRegressor(n_estimators=400, verbose=-1);
reg_CS.fit(xtrain_CS, ytrain_CS)

#Train
print(len(xtrain_CS), len(ytrain_CS))
print("Train_R2", r2_score(ytrain_CS, reg_CS.predict(xtrain_CS)))
print("Train_MSE", mean_squared_error(ytrain_CS, reg_CS.predict(xtrain_CS)))

1158 1158
Train_R2 0.9971957168669455
Train_MSE 1.2941088317992953


In [44]:
## from statsmodels.stats.outliers_influence import variance_inflation_factor
# VIF dataframe
VIF_CS = df_CS_1.copy()
VIF_CS = VIF_CS.drop(['CS Value'], axis =1).dropna()

vif_data = pd.DataFrame()
vif_data["feature"] = VIF_CS.columns
# calculating VIF for each feature
vif_data["VIF"] = [variance_inflation_factor(VIF_CS.values, i)
                          for i in range(len(VIF_CS.columns))]
  
print(vif_data)

              feature        VIF
0              Cement  41.389589
1               Water  36.903732
2              Fine A  38.590262
3            Coarse A  42.818927
4     Max CA Agg (mm)  14.416799
5                  SP   6.300025
6   Lime stone powder   2.514979
7          Metakaolin   1.576364
8               GGBFS   2.687784
9         Silica Fume   1.685650
10            Fly Ash   3.628250
11        Steel Fibre   4.344494
12          S Fibre D  72.592491
13          S Fibre L  65.055276
14             CS Age   1.560521
15            Co Type   6.395584


#### ViF CS

In [45]:
df_CS_1 = df_CS_0[['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                   'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'CS Age', 'Co Type', 
                   'CS Value']] 
df_CS_ViF = df_CS_1.dropna()
print(len(df_CS_ViF))
#############################################################Data_vif1 'Cement' X0
x_vif1 = df_CS_ViF[['Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L',
                'CS Age', 'Co Type']]
y_vif1 = df_CS_ViF[['Cement']]

#sc_vif1 = MinMaxScaler()
#x_vif1 = sc_vif1.fit_transform(x_vif1)

reg_vif1 = RandomForestRegressor(n_estimators=10)
#reg_vif1 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif1.fit(x_vif1, np.array(y_vif1).ravel());
#############################################################Data_vif1

#############################################################Data_vif2 'Water' X1
x_vif2 = df_CS_ViF[['Cement', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L',
                'CS Age', 'Co Type']]
y_vif2 = df_CS_ViF[['Water']]

#sc_vif2 = MinMaxScaler()
#x_vif2 = sc_vif2.fit_transform(x_vif2)

reg_vif2 = RandomForestRegressor(n_estimators=10)
#reg_vif2 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif2.fit(x_vif2, np.array(y_vif2).ravel());
#############################################################Data_vif2

#############################################################Data_vif3 'Fag' X2
x_vif3 = df_CS_ViF[['Cement', 'Water', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L',
                'CS Age', 'Co Type']]
y_vif3 = df_CS_ViF[['Fine A']]

#sc_vif3 = MinMaxScaler()
#x_vif3 = sc_vif3.fit_transform(x_vif3)

reg_vif3 = RandomForestRegressor(n_estimators=10)
#reg_vif3 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif3.fit(x_vif3, np.array(y_vif3).ravel());
#############################################################Data_vif3

#############################################################Data_vif4 'Cag' X3
x_vif4 = df_CS_ViF[['Cement', 'Water', 'Fine A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 
                    'Metakaolin','GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'CS Age', 'Co Type']]
y_vif4 = df_CS_ViF[['Coarse A']]

#sc_vif4 = MinMaxScaler()
#x_vif4 = sc_vif4.fit_transform(x_vif4)

reg_vif4 = RandomForestRegressor(n_estimators=10)
#reg_vif4 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif4.fit(x_vif4, np.array(y_vif4).ravel());
#############################################################Data_vif4

#############################################################Data_vif5 'Max CA Agg (mm)' X4
x_vif5 = df_CS_ViF[['Cement', 'Water', 'Fine A', 'Coarse A', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L',
                'CS Age', 'Co Type']]
y_vif5 = df_CS_ViF[['Max CA Agg (mm)']]

#sc_vif5 = MinMaxScaler()
#x_vif5 = sc_vif5.fit_transform(x_vif5)

reg_vif5 = RandomForestRegressor(n_estimators=10)
#reg_vif5 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif5.fit(x_vif5, np.array(y_vif5).ravel());
#############################################################Data_vif5

#############################################################Data_vif6 'S Fibre D' X12
x_vif6 = df_CS_ViF[['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre L',
                'CS Age', 'Co Type']]
y_vif6 = df_CS_ViF[['S Fibre D']]

#sc_vif6 = MinMaxScaler()
#x_vif6 = sc_vif6.fit_transform(x_vif6)

reg_vif6 = RandomForestRegressor(n_estimators=10)
#reg_vif6 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif6.fit(x_vif6, np.array(y_vif6).ravel());

#############################################################Data_vif6

#############################################################Data_vif7 'S Fibre L' X13
x_vif7 = df_CS_ViF[['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D',
                'CS Age', 'Co Type']]
y_vif7 = df_CS_ViF[['S Fibre L']]

#sc_vif7 = MinMaxScaler()
#x_vif7 = sc_vif7.fit_transform(x_vif7)

reg_vif7 = RandomForestRegressor(n_estimators=10)
#reg_vif7 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif7.fit(x_vif7, np.array(y_vif7).ravel());

#############################################################Data_vif7

1158


### ViF MoR

In [46]:
df_MoR_1 = df_MoR_0[['FA/CM', 'FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Max CA Agg (mm)', 'Converted CS', 'FS Value']]     
df_MoR_ViF = df_MoR_1.dropna()
print(len(df_MoR_ViF))
#############################################################Data_vif7 'S Fibre L' X13
x_vif_MoR1 = df_MoR_ViF[['FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Converted CS', 'Max CA Agg (mm)']]
y_vif_MoR1 = df_MoR_ViF[['FA/CM']]

#sc_vif_MoR1 = MinMaxScaler()
#x_vif_MoR1 = sc_vif_MoR1.fit_transform(x_vif_MoR1)

reg_vif_MoR1 = RandomForestRegressor(n_estimators=10)
#reg_vif_MoR1 = LGBMRegressor(n_estimators=1, verbose=-1);
reg_vif_MoR1.fit(x_vif_MoR1, np.array(y_vif_MoR1).ravel());
#############################################################Data_vif7

439


#### Examples

In [47]:
x = np.array([1, 2, 3, 4, 5])

In [48]:
np.hstack((x[:1],x[2:])).reshape(1,-1)

array([[1, 3, 4, 5]])

In [49]:
#Example
print(np.array([1, 2, 3, 4, 5])[:3])
print(np.array([1, 2, 3, 4, 5])[4:])

[1 2 3]
[5]


In [50]:
def VIF1(x): #Cement 
    return reg_vif1.predict(x[1:].reshape(1,-1))
def VIF2(x): #Water
    return reg_vif2.predict(np.hstack((x[:1],x[2:])).reshape(1,-1))
def VIF3(x): #Fag
    return reg_vif3.predict(np.hstack((x[:2],x[3:])).reshape(1,-1))
def VIF4(x): #Cag
    return reg_vif4.predict(np.hstack((x[:3],x[4:])).reshape(1,-1))
def VIF5(x): #Max Cag Size
    return reg_vif5.predict(np.hstack((x[:4],x[5:])).reshape(1,-1))
def VIF6(x): #S Fibre D
    return reg_vif6.predict(np.hstack((x[:12],x[13:])).reshape(1,-1))
def VIF7(x): #S Fibre L
    return reg_vif7.predict(np.hstack((x[:13],x[14:])).reshape(1,-1))

In [51]:
def VIF_MoR1(x): #S FA/CM
    a2 = x[2]/x[3] #FA/CA
    return reg_vif_MoR1.predict(np.array([a2, x[11], x[12], x[13], x[4], CS_Model(x).item()]).reshape(1,-1))

In [52]:
reg_vif_MoR1.predict(np.array([0.66, 118, 0.55, 35, 110.8, 16.]).reshape(1,-1))

array([1.17159634])

### Pyomo

'FA/CM', 'FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Max CA Agg (mm)', 'Converted CS'

    0       1         2          3            4              5            6                 7
'Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
    8         9             10           11            12           13        14         15
'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'CS Age', 'Co Type'

x1  x[0]  Cement
x2  x[1]  Water
x3  x[2]  Fag
x4  x[3]  Cag
x5  x[4]  Cagmax
x6  x[5]  SP
x7  x[6]  LP
x8  x[7]  M
x9  x[8]  GBFS
x10 x[9]  SF
x11 x[10] FA
x12 x[11] StF
x13 x[12] StFd
x14 x[13] StFl
x15 x[14] Age
x16 x[15] Type

In [53]:
def CS_Model(x):
    return reg_CS.predict(x.reshape(1,-1))

#'FA/CM', 'FA/CA', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'Max CA Agg (mm)', 'Converted CS'

def MoR_Model(x):
    a1 = (x[2])/(x[0] + x[6] + x[7] + x[8] + x[9] + x[10]) #FA/CM
    a2 = x[2]/x[3] #FA/CA
    '''
    print(reg_MoR.predict(np.array([1.85, 0.66, 118, 0.55, 35, 50.8, 16.]).reshape(1,-1)),
      reg_MoR.predict(np.array([1.85, 0.67, 118, 0.55, 35, 102, 16.]).reshape(1,-1)))
      '''
    #return reg_MoR.predict(np.array([a1, a2, x[11], x[12], x[13], x[4], 200]).reshape(1,-1))
    return reg_MoR.predict(np.array([a1, a2, x[11], x[12], x[13], x[4], CS_Model(x).item()]).reshape(1,-1))

def GWP(x):
    Co2 = (0.885 * x[0]              # cement
           + 0.0025 * x[1]           # water
           + 0.0032 * (x[2] + x[3])  # FA+CA
           + 1.11 * x[5]             # SP
           + 1.6 * x[11])            # Steel fiber  
    return Co2

def CoP(x):
    CoP = (0.2 * x[0]       # cement
           + 0.005 * x[1]   # water
           + 0.4 * x[9]     # SF
           + 0.05 * x[2]    # Fag
           + 0.11 * x[10]   # fly ash
           + 0.06 * x[3]    # Cag
           + 3.8 * x[5]     # SP
           + 0.18 * x[8]    # GBFS
           + 0.4 *x[7]      # Metakaolin  
           + 0.28 *x[6]     # Lime stone powder
           + 1.15 *x[11])    # Steel Fiber
    return CoP

In [54]:
from pymoo.core.problem import ElementwiseProblem
from pymoo.core.variable import Real, Integer, Choice, Binary

class MyProblem(ElementwiseProblem):
    
    def __init__(self, **kwargs):
        vars = {
            "x1": Real(bounds=(80, 600)), ##cement
            "x2": Real(bounds=(125, 320)), ##water
            "x3": Real(bounds=(280, 1014)), ##fag
            "x4": Real(bounds=(497, 1385)), #cag
            
            "x5": Choice(options=[10.  , 12.5 , 15.  , 16.  , 19.  , 19.1 , 20.  , 22.  , 25. ]), ##cag max size
            #"x5": Choice(options=[10., 12.5, 15., 19., 20.]), ##cag max size
            
            "x6": Real(bounds=(0, 13.75)), ##SP
            
            #"x7": Real(bounds=(0, 152)), ##LSP
            "x7": Choice(options=[0]), ##LSP
            
            #"x8": Real(bounds=(0, 88.4)), ##M
            "x8": Choice(options=[0]), ##M
            
            "x9": Real(bounds=(0, 320)), ##GBFS
            #"x9": Choice(options=[0]), ##GBFS
            
            "x10": Real(bounds=(0, 102)), ##SF
            #"x10": Choice(options=[0]), ##SF 
            
            
            "x11": Real(bounds=(0, 545)), ##FA
            #"x11": Choice(options=[0]), ##FA
            
            "x12":Real(bounds=(15, 120)), ##StF
            #"x12": Choice(options=[0]), ##StF
            
            "x13": Choice(options=[0.38 , 0.5  , 0.55 , 0.6  , 0.615, 0.62 , 0.625, 0.75 , 0.8]), ##d
            #"x13": Choice(options=[0]), ##d
            
            "x14": Choice(options=[30, 31, 35, 40, 50, 51, 60]), ##l
            #"x14": Choice(options=[0]), ##l
            
            "x15": Choice(options=[28]), ##Age
            #x15": Choice(options=[28]), ##Age
            
            "x16": Choice(options=[0]), ##Type
            
        }
        super().__init__(vars=vars, n_obj=2, n_constr=22,**kwargs)    


    def _evaluate(self, X, out, *args, **kwargs):
        x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16 =\
        X["x1"], X["x2"], X["x3"], X["x4"], X["x5"], X["x6"], X["x7"], X["x8"], X["x9"], X["x10"], X["x11"],\
        X["x12"], X["x13"], X["x14"], X["x15"], X["x16"]
        
        Models_input = np.array([x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16])
        
        #############################################Objectives
        f1 = GWP(Models_input)
        f2 = CoP(Models_input)
        #f3 = 1/CS_Model(Models_input)
        
        
        #############################################Constraints
        ###Fiber Combination
        allowed_combinations = [(0.0, 0), (0.8, 51), (0.75, 60), (0.75, 30), (0.55, 35), 
                                (0.6, 30), (0.7, 70), (0.9, 60), (0.8, 50), (0.5, 30), 
                                (0.625, 50), (0.62, 40), (0.62, 50), (0.615, 40), (0.55, 30)]
            # Add more allowed combinations if needed.
            
        # Check if a given pair is allowed
        def is_combination_allowed(x13, x14):
            return any(x13 == a and x14 == b for a, b in allowed_combinations)

        # In your constraints section, add:
        comb_g = 0 if is_combination_allowed(x13, x14) else 1        


        
        ## Volume Constraints
        #       C       W       Fag    Cag      SP     LP      Met     GBFS     SF       FA       StF
        v1 = (x1/3130+x2/1000+x3/2600+x4/2700+x6/1150+x7/2700+x8/2650+x9/2900+x10/1900+x11/2500+x12/7850)-1.1
        v2 = 0.90-(x1/3130+x2/1000+x3/2600+x4/2700+x6/1150+x7/2700+x8/2650+x9/2900+x10/1900+x11/2500+x12/7850)
        
        ## RAtio Constraints
        #0.242 < x2 / (x1 + x7 + x8 + x9 + x10 + x11) < 0.72  W/Binder
        r1 = 0.242 - (x2 / (x1 + x7 + x8 + x9 + x10 + x11))
        r2 = (x2 / (x1 + x7 + x8 + x9 + x10 + x11)) - 0.72
        
        #0.212 < x3 / (x3 + x4) < 0.77                        Fag/(Fag+Cag)
        r3 = 0.212 - (x3 / (x3 + x4))
        r4 = (x3 / (x3 + x4)) - 0.77        
        
        # 0 < ((x7 + x8 + x9 + x10 + x11) / x1) < 4.09        SCMs/C
        r5 = 0 - ((x7 + x8 + x9 + x10 + x11) / x1)
        r6 = ((x7 + x8 + x9 + x10 + x11) / x1) - 4.09      

        ###################################### ML Constraints 
        
        ##Modelling MoR
        g1 = -MoR_Model(Models_input) + 7.5
        g2 = MoR_Model(Models_input) - 8.5

        ##Modelling CS
        #g1 = -CS_Model(Models_input) + 80
        #g2 = CS_Model(Models_input) - 190 
        
        
        ## Multicolinearity Constraints
        Acceptable_range1 = 0.15 
        Acceptable_range2 = 0.25
        ##################################   CS  #######################################
        # VIF1 Cement
        g111 = (x1 - x1*Acceptable_range1) - VIF1(Models_input)                            ##1
        g112 = VIF1(Models_input) - (x1 + x1*Acceptable_range1)                            ##1
        
        #VIF2 Water
        g121 = (x2 - x2*Acceptable_range1) - VIF2(Models_input)                            ##1
        g122 = VIF2(Models_input) - (x2 + x2*Acceptable_range1)                            ##1
        
        #VIF3 Fag
        g131 = (x3 - x3*Acceptable_range1) - VIF3(Models_input)                            ##1
        g132 = VIF3(Models_input) - (x3 + x3*Acceptable_range1)                            ##1
        
        #VIF4 Cag
        g141 = (x4 - x4*Acceptable_range1) - VIF4(Models_input)                            ##1
        g142 = VIF4(Models_input) - (x4 + x4*Acceptable_range1)                            ##1
        
        #VIF5 Cagmax
        g151 = (x5 - x5*Acceptable_range2) - VIF5(Models_input)                            ##2
        g152 = VIF5(Models_input) - (x5 + x5*Acceptable_range2)                            ##2
        
        #VIF6 StFd
        #g161 = (x13 - x13*Acceptable_range2) - VIF6(Models_input)                          ##2
        #g162 = VIF6(Models_input) - (x13 + x13*Acceptable_range2)                          ##2
        
        #VIF7 StFl
        #g171 = (x14 - x14*Acceptable_range2) - VIF7(Models_input)                          ##2
        #g172 = VIF7(Models_input) - (x14 + x14*Acceptable_range2)                          ##2
        
        ##################################   MoR  #######################################
        # VIF1 FA/CM
        FA_CM = (x3)/(x1 + x7 + x8 + x9 + x10 + x11) #FA/CM
        g211 = (FA_CM - FA_CM*Acceptable_range1) - VIF_MoR1(Models_input)                  ##1
        g212 = VIF_MoR1(Models_input) - (FA_CM + FA_CM*Acceptable_range1)                  ##1
        

        
        out["F"] = [f1, f2]
        out["G"] = [v1, v2, 
                    r1, r2, r3, r4, r5, r6,  
                    g1.item(), g2.item(),
                    g111.item(), g112.item(),
                    g121.item(), g122.item(),
                    g131.item(), g132.item(),
                    g141.item(), g142.item(), 
                    g151.item(), g152.item(),
                    #g161.item(), g162.item(),       
                    #g171.item(), g172.item(),
                    #gx1.item(), gx2.item(),
                    #comb_g.item(),
                    g211.item(), g212.item()]


problem = MyProblem()

#### MixedVariableGA

In [55]:
import pymoo
print(pymoo.__version__)

0.6.0


In [57]:
from pymoo.factory import get_termination
from pymoo.core.mixed import MixedVariableGA
from pymoo.optimize import minimize
import warnings
warnings.filterwarnings('ignore')

from pymoo.algorithms.moo.nsga2 import RankAndCrowdingSurvival

termination = get_termination("n_gen", 2000)

algorithm = MixedVariableGA(pop=100000000, survival=RankAndCrowdingSurvival())
res = minimize(problem,
               algorithm,
               termination,
               save_history=False,
               verbose=True)

n_gen  |  n_eval  |     cv_min    |     cv_avg    |     f_avg     |     f_min    
     1 |       50 |  1.280745E+01 |  4.389874E+02 |             - |             -
     2 |      100 |  1.280745E+01 |  2.221176E+02 |             - |             -
     3 |      150 |  1.051843E+01 |  1.433774E+02 |             - |             -
     4 |      200 |  5.7816731971 |  8.753401E+01 |             - |             -
     5 |      250 |  1.8299934301 |  5.530664E+01 |             - |             -
     6 |      300 |  0.000000E+00 |  2.842386E+01 |  3.167997E+02 |  3.167997E+02
     7 |      350 |  0.000000E+00 |  1.872918E+01 |  3.167997E+02 |  3.167997E+02
     8 |      400 |  0.000000E+00 |  1.159514E+01 |  2.598606E+02 |  2.029216E+02
     9 |      450 |  0.000000E+00 |  7.3655725688 |  2.598606E+02 |  2.029216E+02
    10 |      500 |  0.000000E+00 |  4.3430825470 |  2.598606E+02 |  2.029216E+02
    11 |      550 |  0.000000E+00 |  3.1337739218 |  2.598606E+02 |  2.029216E+02
    12 |      60

### Optimisation of the results

In [59]:
res.F

array([[119.30011274, 171.22329655],
       [119.34257821, 170.44036932],
       [119.48935562, 170.25315127],
       [116.77171173, 175.49286251],
       [119.34323585, 170.43657448],
       [119.51068925, 170.25285837],
       [119.48862977, 170.2640681 ],
       [112.92738891, 180.03663695],
       [115.0187872 , 179.73958631],
       [115.16952136, 179.61922446],
       [119.34203597, 170.45854043]])

In [60]:
res.X

array([{'x1': 101.16340334812979, 'x2': 166.1467992522949, 'x3': 771.3809641095662, 'x4': 901.663411351361, 'x6': 0.0012322523933872142, 'x9': 167.46988970415876, 'x10': 0.09021856907632687, 'x11': 91.41510571106912, 'x12': 15.000014987817245, 'x5': 15.0, 'x7': 0, 'x8': 0, 'x13': 0.8, 'x14': 51, 'x15': 28, 'x16': 0},
       {'x1': 101.21232779317695, 'x2': 166.0114671191031, 'x3': 771.3548153295901, 'x4': 901.6526776305715, 'x6': 0.0009130954296952651, 'x9': 163.24548344477415, 'x10': 0.018308817151062712, 'x11': 91.4178481510968, 'x12': 15.000001209646525, 'x5': 15.0, 'x7': 0, 'x8': 0, 'x13': 0.8, 'x14': 51, 'x15': 28, 'x16': 0},
       {'x1': 101.3808568494358, 'x2': 166.020827302383, 'x3': 770.4021928448497, 'x4': 901.6558059328004, 'x6': 0.00148979344708663, 'x9': 162.2942527329338, 'x10': 0.007680790695875466, 'x11': 91.41558592740822, 'x12': 15.000003732983451, 'x5': 15.0, 'x7': 0, 'x8': 0, 'x13': 0.8, 'x14': 51, 'x15': 28, 'x16': 0},
       {'x1': 96.34881540802041, 'x2': 166.00

In [61]:
res.X[0].values()

dict_values([101.16340334812979, 166.1467992522949, 771.3809641095662, 901.663411351361, 0.0012322523933872142, 167.46988970415876, 0.09021856907632687, 91.41510571106912, 15.000014987817245, 15.0, 0, 0, 0.8, 51, 28, 0])

In [62]:
# Sort dictionary by keys
sorted_data = {k: res.X[0][k] for k in sorted(res.X[0].keys(), key=lambda x: int(x[1:]))}

print(sorted_data)

{'x1': 101.16340334812979, 'x2': 166.1467992522949, 'x3': 771.3809641095662, 'x4': 901.663411351361, 'x5': 15.0, 'x6': 0.0012322523933872142, 'x7': 0, 'x8': 0, 'x9': 167.46988970415876, 'x10': 0.09021856907632687, 'x11': 91.41510571106912, 'x12': 15.000014987817245, 'x13': 0.8, 'x14': 51, 'x15': 28, 'x16': 0}


In [63]:
sorted_data

{'x1': 101.16340334812979,
 'x2': 166.1467992522949,
 'x3': 771.3809641095662,
 'x4': 901.663411351361,
 'x5': 15.0,
 'x6': 0.0012322523933872142,
 'x7': 0,
 'x8': 0,
 'x9': 167.46988970415876,
 'x10': 0.09021856907632687,
 'x11': 91.41510571106912,
 'x12': 15.000014987817245,
 'x13': 0.8,
 'x14': 51,
 'x15': 28,
 'x16': 0}

In [64]:
new_keys = ['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
            'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'CS Age', 'Co Type']

new_data = {new_keys[i]: value for i, value in enumerate(sorted_data.values())}
print(new_data)

{'Cement': 101.16340334812979, 'Water': 166.1467992522949, 'Fine A': 771.3809641095662, 'Coarse A': 901.663411351361, 'Max CA Agg (mm)': 15.0, 'SP': 0.0012322523933872142, 'Lime stone powder': 0, 'Metakaolin': 0, 'GGBFS': 167.46988970415876, 'Silica Fume': 0.09021856907632687, 'Fly Ash': 91.41510571106912, 'Steel Fibre': 15.000014987817245, 'S Fibre D': 0.8, 'S Fibre L': 51, 'CS Age': 28, 'Co Type': 0}


#### Double Checking the results

In [65]:
reg_CS.predict(np.array(list(sorted_data.values())).reshape(1, -1))

array([46.28169529])

In [66]:
CS_Model(np.array(list(sorted_data.values())))

array([46.28169529])

In [67]:
MoR_Model(np.array(list(sorted_data.values())))

array([7.52933393])

In [68]:
for i in range(len(res.X)):
    print(res.X[i])

{'x1': 101.16340334812979, 'x2': 166.1467992522949, 'x3': 771.3809641095662, 'x4': 901.663411351361, 'x6': 0.0012322523933872142, 'x9': 167.46988970415876, 'x10': 0.09021856907632687, 'x11': 91.41510571106912, 'x12': 15.000014987817245, 'x5': 15.0, 'x7': 0, 'x8': 0, 'x13': 0.8, 'x14': 51, 'x15': 28, 'x16': 0}
{'x1': 101.21232779317695, 'x2': 166.0114671191031, 'x3': 771.3548153295901, 'x4': 901.6526776305715, 'x6': 0.0009130954296952651, 'x9': 163.24548344477415, 'x10': 0.018308817151062712, 'x11': 91.4178481510968, 'x12': 15.000001209646525, 'x5': 15.0, 'x7': 0, 'x8': 0, 'x13': 0.8, 'x14': 51, 'x15': 28, 'x16': 0}
{'x1': 101.3808568494358, 'x2': 166.020827302383, 'x3': 770.4021928448497, 'x4': 901.6558059328004, 'x6': 0.00148979344708663, 'x9': 162.2942527329338, 'x10': 0.007680790695875466, 'x11': 91.41558592740822, 'x12': 15.000003732983451, 'x5': 15.0, 'x7': 0, 'x8': 0, 'x13': 0.8, 'x14': 51, 'x15': 28, 'x16': 0}
{'x1': 96.34881540802041, 'x2': 166.00713338814813, 'x3': 770.4852897

In [69]:
res.F[i]

array([119.34203597, 170.45854043])

In [70]:
import pandas as pd

# Assuming your original code
data = []
for i in range(len(res.X)):
    sorted_data = {k: res.X[i][k] for k in sorted(res.X[i].keys(), key=lambda x: int(x[1:]))}
    V_FA_CM = list(sorted_data.values())
    
    data.append(list(sorted_data.values()) + list(res.F[i]) # Data + Objectives(F1, F2)
                
                + [float(reg_CS.predict(np.array(list(sorted_data.values())).reshape(1, -1))[0])] # CS Prediciton
                + [(float(MoR_Model(np.array(list(sorted_data.values())))[0]))] # MoR Prediciton
                
                + [VIF1(np.array(list(sorted_data.values())))[0], round(np.array(list(sorted_data.values()))[0], 2)]
                + [VIF2(np.array(list(sorted_data.values())))[0], round(np.array(list(sorted_data.values()))[1], 2)]
                + [VIF3(np.array(list(sorted_data.values())))[0], round(np.array(list(sorted_data.values()))[2], 2)]
                + [VIF4(np.array(list(sorted_data.values())))[0], round(np.array(list(sorted_data.values()))[3], 2)]
                + [VIF5(np.array(list(sorted_data.values())))[0], round(np.array(list(sorted_data.values()))[4], 2)]
                + [VIF6(np.array(list(sorted_data.values())))[0], round(np.array(list(sorted_data.values()))[12], 2)]
                + [VIF7(np.array(list(sorted_data.values())))[0], round(np.array(list(sorted_data.values()))[13], 2)]

                + [round(VIF_MoR1(np.array(list(sorted_data.values()))).item(), 2),
                 round((V_FA_CM[2])/(V_FA_CM[0] + V_FA_CM[6] + V_FA_CM[7] + V_FA_CM[8] + V_FA_CM[9] + V_FA_CM[10]), 2)]) 

# Create a DataFrame
df = pd.DataFrame(data)

column_names = ['Cement', 'Water', 'Fine A', 'Coarse A', 'Max CA Agg (mm)', 'SP', 'Lime stone powder', 'Metakaolin',
                'GGBFS', 'Silica Fume', 'Fly Ash', 'Steel Fibre', 'S Fibre D', 'S Fibre L', 'CS Age', 'Co Type',
                'GWP', 'CoP', #'F3',
                'CS', 'MoR', 
                'V_C', 'C', 'V_W', 'VW', 'V_Fag', 'Fag', 'V_Cag', 'Cag', 
                'V_Cagmax', 'Cagmax', 'V_StFd', 'StFd', 'V_StFl', 'StFl', 'V_FA/CM', 'FA_CM']

df = pd.DataFrame(data, columns=column_names)

print(df)

        Cement       Water      Fine A    Coarse A  Max CA Agg (mm)        SP  \
0   101.163403  166.146799  771.380964  901.663411             15.0  0.001232   
1   101.212328  166.011467  771.354815  901.652678             15.0  0.000913   
2   101.380857  166.020827  770.402193  901.655806             15.0  0.001490   
3    96.348815  166.007133  770.485290  889.147384             15.0  1.601050   
4   101.212328  166.010493  771.356344  901.655834             15.0  0.001491   
5   101.405105  166.545774  770.271582  901.655929             15.0  0.000574   
6   101.381067  166.187752  770.301473  901.661023             15.0  0.000573   
7    91.944873  166.531857  770.470786  889.148052             15.0  1.647807   
8    94.371295  166.003346  757.738406  901.001204             19.0  1.601088   
9    94.740860  166.010504  770.423784  889.148054             19.0  1.436764   
10  101.212328  166.010470  771.350002  901.652678             15.0  0.000441   

    Lime stone powder  Meta

In [71]:
df

Cement       Water      Fine A    Coarse A  Max CA Agg (mm)        SP  \
0   101.163403  166.146799  771.380964  901.663411             15.0  0.001232   
1   101.212328  166.011467  771.354815  901.652678             15.0  0.000913   
2   101.380857  166.020827  770.402193  901.655806             15.0  0.001490   
3    96.348815  166.007133  770.485290  889.147384             15.0  1.601050   
4   101.212328  166.010493  771.356344  901.655834             15.0  0.001491   
5   101.405105  166.545774  770.271582  901.655929             15.0  0.000574   
6   101.381067  166.187752  770.301473  901.661023             15.0  0.000573   
7    91.944873  166.531857  770.470786  889.148052             15.0  1.647807   
8    94.371295  166.003346  757.738406  901.001204             19.0  1.601088   
9    94.740860  166.010504  770.423784  889.148054             19.0  1.436764   
10  101.212328  166.010470  771.350002  901.652678             15.0  0.000441   

    Lime stone powder  Metakaolin       GGBFS  Silica Fume    Fly Ash  \
0                   0           0  167.469890     0.090219  91.415106   
1                   0           0  163.245483     0.018309  91.417848   
2                   0           0  162.294253     0.007681  91.415586   
3                   0           0  167.391141     0.000380  91.412803   
4                   0           0  163.206302     0.020308  91.417848   
5                   0           0  162.339516     0.001971  91.382635   
6                   0           0  162.316715     0.024532  91.483473   
7                   0           0  167.400600    13.108080  91.414306   
8                   0           0  165.787512    12.143837  91.408088   
9                   0           0  167.402192    12.659148  91.479372   
10                  0           0  163.245483     0.069156  91.416692   

    Steel Fibre  S Fibre D  S Fibre L  CS Age  Co Type         GWP  \
0     15.000015        0.8         51      28        0  119.300113   
1     15.000001        0.8         51      28        0  119.342578   
2     15.000004        0.8         51      28        0  119.489356   
3     15.000002        0.8         51      28        0  116.771712   
4     15.000004        0.8         51      28        0  119.343236   
5     15.000001        0.8         51      28        0  119.510689   
6     15.000000        0.8         51      28        0  119.488630   
7     15.000000        0.8         51      28        0  112.927389   
8     15.000005        0.8         51      28        0  115.018787   
9     15.002123        0.8         51      28        0  115.169521   
10    15.000001        0.8         51      28        0  119.342036   

           CoP         CS       MoR    V_C       C     V_W      VW  V_Fag  \
0   171.223297  46.281695  7.529334  116.3  101.16  190.15  166.15  823.9   
1   170.440369  46.288999  7.529334  116.3  101.21  190.15  166.01  823.9   
2   170.253151  46.288999  7.529334  116.3  101.38  190.15  166.02  823.9   
3   175.492863  46.818376  7.518200  110.8   96.35  168.43  166.01  833.4   
4   170.436574  46.288999  7.529334  116.3  101.21  190.15  166.01  823.9   
5   170.252858  46.288999  7.529334  116.3  101.41  190.15  166.55  823.9   
6   170.264068  46.288999  7.529334  116.3  101.38  190.15  166.19  823.9   
7   180.036637  47.669125  7.748611  103.4   91.94  168.43  166.53  842.0   
8   179.739586  46.196315  7.798799  103.4   94.37  156.75  166.00  831.5   
9   179.619224  46.372233  7.652186  108.9   94.74  175.83  166.01  842.0   
10  170.458540  46.288999  7.529334  116.3  101.21  190.15  166.01  823.9   

       Fag   V_Cag     Cag  V_Cagmax  Cagmax  V_StFd  StFd  V_StFl  StFl  \
0   771.38  1036.9  901.66      14.5    15.0   0.752   0.8    51.5  51.0   
1   771.35  1036.9  901.65      14.5    15.0   0.752   0.8    51.5  51.0   
2   770.40  1036.9  901.66      14.5    15.0   0.752   0.8    51.5  51.0   
3   770.49  1022.5  889.15      14.5    15.0   0.752   0.8    51.5  51.0   
4   771.36  

In [35]:
import pandas as pd

# Set the display options to show the entire DataFrame
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Apply the rounding to two decimals for the entire dataframe
rounded_df = df.round(2)

# Display the dataframe
rounded_df

Cement   Water  Fine A  Coarse A  Max CA Agg (mm)    SP  Lime stone powder  \
0  232.54  167.44  503.39   1138.32             19.1  0.00                  0   
1  232.54  167.44  504.61   1142.91             19.1  0.00                  0   
2  232.54  167.44  503.28   1138.32             19.1  0.00                  0   
3  232.54  167.44  508.70   1138.26             19.1  0.00                  0   
4  254.08  167.31  508.93   1137.65             19.1  0.00                  0   
5  232.54  167.44  509.64   1138.26             19.1  0.00                  0   
6  254.12  164.39  503.19   1138.00             19.0  0.01                  0   

   Metakaolin   GGBFS  Silica Fume  Fly Ash  Steel Fibre  S Fibre D  \
0           0  162.35        41.54    77.44        51.36        0.8   
1           0  162.35        42.06    77.47        51.31        0.8   
2           0  162.35        41.54    77.52        51.36        0.8   
3           0  160.45        41.54    78.55        51.35        0.8   
4           0   96.99        41.70    78.51        41.68        0.8   
5           0  160.41        41.54    77.47        51.35        0.8   
6           0   97.10        41.41    78.56        41.71        0.8   

   S Fibre L  CS Age  Co Type     GWP     CoP     CS   MoR     V_C       C  \
0         51      28        0  293.65  254.24  58.39  7.54  256.40  232.54   
1         51      28        0  293.58  254.73  58.39  7.54  256.40  232.54   
2         51      28        0  293.65  254.24  58.39  7.54  256.40  232.54   
3         51      28        0  293.65  254.27  58.39  7.54  256.40  232.54   
4         51      28        0  297.24  236.07  64.85  7.51  281.38  254.08   
5         51      28        0  293.65  254.19  58.39  7.54  256.40  232.54   
6         51      28        0  297.31  235.78  64.77  7.51  281.38  254.12   

     V_W      VW   V_Fag     Fag   V_Cag      Cag  V_Cagmax  Cagmax  V_StFd  \
0  188.5  167.44  572.97  503.39  1094.0  1138.32     20.15    19.1    0.77   
1  180.9  167.44  579.27  504.61  1094.0  1142.91     20.15    19.1    0.77   
2  188.5  167.44  572.97  503.28  1094.0  1138.32     20.15    19.1    0.77   
3  188.5  167.44  572.97  508.70  1095.0  1138.26     20.15    19.1    0.77   
4  188.5  167.31  581.27  508.93  1095.0  1137.65     19.25    19.1    0.77   
5  188.5  167.44  572.97  509.64  1095.0  1138.26     20.15    19.1    0.77   
6  188.5  164.39  572.97  503.19  1094.0  1138.00     19.25    19.0    0.77   

   StFd  V_StFl  StFl  V_FA/CM  FA_CM  
0   0.8    52.4  51.0     1.01   0.98  
1   0.8    52.4  51.0     1.01   0.98  
2   0.8    52.4  51.0     1.01   0.98  
3   0.8    52.4  51.0     1.01   0.99  
4   0.8    52.4  51.0     1.01   1.08  
5   0.8    52.4  51.0     1.01   1.00  
6   0.8    52.4  51.0     1.01   1.07

In [49]:
x = list(rounded_df.loc[0,:])[:16]

In [50]:
MoR_Model(np.array(x))

array([7.5497129])

In [142]:
#df.to_excel("df1.xlsx")

In [147]:
#DF = pd.read_excel("./Designed_Mixes/df1.xlsx")
DF = pd.read_excel("./Designed_Mixes/df_Final.xlsx")

In [148]:
df_combined = DF.append(df, ignore_index=True)

In [149]:
df_combined.to_excel("./Designed_Mixes/df_Final.xlsx")

PermissionError: [Errno 13] Permission denied: './Designed_Mixes/df_Final.xlsx'